// ==========================================================================
// Manually maintained DAO (not generated by GoFrame CLI).
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SupportAgentPresenceDao is the data access object for the table hg_support_agent_presence.
type SupportAgentPresenceDao struct {
	table    string
	group    string
	columns  SupportAgentPresenceColumns
	handlers []gdb.ModelHandler
}

type SupportAgentPresenceColumns struct {
	AgentId    string
	Online     string
	LastSeenAt string
	UpdatedAt  string
}

var supportAgentPresenceColumns = SupportAgentPresenceColumns{
	AgentId:    "agent_id",
	Online:     "online",
	LastSeenAt: "last_seen_at",
	UpdatedAt:  "updated_at",
}

func NewSupportAgentPresenceDao(handlers ...gdb.ModelHandler) *SupportAgentPresenceDao {
	return &SupportAgentPresenceDao{
		group:    "default",
		table:    "hg_support_agent_presence",
		columns:  supportAgentPresenceColumns,
		handlers: handlers,
	}
}

func (dao *SupportAgentPresenceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

func (dao *SupportAgentPresenceDao) Table() string {
	return dao.table
}

func (dao *SupportAgentPresenceDao) Columns() SupportAgentPresenceColumns {
	return dao.columns
}

func (dao *SupportAgentPresenceDao) Group() string {
	return dao.group
}

func (dao *SupportAgentPresenceDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

func (dao *SupportAgentPresenceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}


