// ==========================================================================
// Manually maintained DAO (not generated by GoFrame CLI).
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SupportCannedReplyDao is the data access object for the table hg_support_canned_reply.
type SupportCannedReplyDao struct {
	table    string
	group    string
	columns  SupportCannedReplyColumns
	handlers []gdb.ModelHandler
}

type SupportCannedReplyColumns struct {
	Id        string
	AgentId   string
	Title     string
	Content   string
	Sort      string
	Status    string
	CreatedAt string
	UpdatedAt string
}

var supportCannedReplyColumns = SupportCannedReplyColumns{
	Id:        "id",
	AgentId:   "agent_id",
	Title:     "title",
	Content:   "content",
	Sort:      "sort",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

func NewSupportCannedReplyDao(handlers ...gdb.ModelHandler) *SupportCannedReplyDao {
	return &SupportCannedReplyDao{
		group:    "default",
		table:    "hg_support_canned_reply",
		columns:  supportCannedReplyColumns,
		handlers: handlers,
	}
}

func (dao *SupportCannedReplyDao) DB() gdb.DB {
	return g.DB(dao.group)
}

func (dao *SupportCannedReplyDao) Table() string {
	return dao.table
}

func (dao *SupportCannedReplyDao) Columns() SupportCannedReplyColumns {
	return dao.columns
}

func (dao *SupportCannedReplyDao) Group() string {
	return dao.group
}

func (dao *SupportCannedReplyDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

func (dao *SupportCannedReplyDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}


