// ==========================================================================
// Manually maintained DAO (not generated by GoFrame CLI).
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SupportMessageDao is the data access object for the table hg_support_message.
type SupportMessageDao struct {
	table    string
	group    string
	columns  SupportMessageColumns
	handlers []gdb.ModelHandler
}

// SupportMessageColumns defines and stores column names for the table hg_support_message.
type SupportMessageColumns struct {
	Id         string
	SessionId  string
	SenderRole string
	SenderId   string
	MsgType    string
	Content    string
	CreatedAt  string
}

var supportMessageColumns = SupportMessageColumns{
	Id:         "id",
	SessionId:  "session_id",
	SenderRole: "sender_role",
	SenderId:   "sender_id",
	MsgType:    "msg_type",
	Content:    "content",
	CreatedAt:  "created_at",
}

func NewSupportMessageDao(handlers ...gdb.ModelHandler) *SupportMessageDao {
	return &SupportMessageDao{
		group:    "default",
		table:    "hg_support_message",
		columns:  supportMessageColumns,
		handlers: handlers,
	}
}

func (dao *SupportMessageDao) DB() gdb.DB {
	return g.DB(dao.group)
}

func (dao *SupportMessageDao) Table() string {
	return dao.table
}

func (dao *SupportMessageDao) Columns() SupportMessageColumns {
	return dao.columns
}

func (dao *SupportMessageDao) Group() string {
	return dao.group
}

func (dao *SupportMessageDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

func (dao *SupportMessageDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}


