// ==========================================================================
// Manually maintained DAO (not generated by GoFrame CLI).
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SupportSessionDao is the data access object for the table hg_support_session.
type SupportSessionDao struct {
	table    string
	group    string
	columns  SupportSessionColumns
	handlers []gdb.ModelHandler
}

// SupportSessionColumns defines and stores column names for the table hg_support_session.
type SupportSessionColumns struct {
	Id         string
	UserId     string
	AgentId    string
	Status     string
	Subject    string
	LastMsg    string
	LastMsgAt  string
	UnreadUser string
	UnreadAgent string
	CreatedAt  string
	UpdatedAt  string
	ClosedAt   string
}

var supportSessionColumns = SupportSessionColumns{
	Id:          "id",
	UserId:      "user_id",
	AgentId:     "agent_id",
	Status:      "status",
	Subject:     "subject",
	LastMsg:     "last_msg",
	LastMsgAt:   "last_msg_at",
	UnreadUser:  "unread_user",
	UnreadAgent: "unread_agent",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	ClosedAt:    "closed_at",
}

// NewSupportSessionDao creates and returns a new DAO object for table data access.
func NewSupportSessionDao(handlers ...gdb.ModelHandler) *SupportSessionDao {
	return &SupportSessionDao{
		group:    "default",
		table:    "hg_support_session",
		columns:  supportSessionColumns,
		handlers: handlers,
	}
}

func (dao *SupportSessionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

func (dao *SupportSessionDao) Table() string {
	return dao.table
}

func (dao *SupportSessionDao) Columns() SupportSessionColumns {
	return dao.columns
}

func (dao *SupportSessionDao) Group() string {
	return dao.group
}

func (dao *SupportSessionDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

func (dao *SupportSessionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}


