// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// adminMenuBackupIconsDao is the data access object for the table hg_admin_menu_backup_icons.
// You can define custom methods on it to extend its functionality as needed.
type adminMenuBackupIconsDao struct {
	*internal.AdminMenuBackupIconsDao
}

var (
	// AdminMenuBackupIcons is a globally accessible object for table hg_admin_menu_backup_icons operations.
	AdminMenuBackupIcons = adminMenuBackupIconsDao{internal.NewAdminMenuBackupIconsDao()}
)

// Add your custom methods and functionality below.
