// =================================================================================
// Manually maintained DAO wrapper (not generated by GoFrame CLI).
// =================================================================================

package dao

import "hotgo/internal/dao/internal"

// supportMessageDao is the data access object for the table hg_support_message.
type supportMessageDao struct {
	*internal.SupportMessageDao
}

var (
	// SupportMessage is a globally accessible object for table hg_support_message operations.
	SupportMessage = supportMessageDao{internal.NewSupportMessageDao()}
)


