// =================================================================================
// Manually maintained DAO wrapper (not generated by GoFrame CLI).
// =================================================================================

package dao

import "hotgo/internal/dao/internal"

// supportCannedReplyDao is the data access object for the table hg_support_canned_reply.
type supportCannedReplyDao struct {
	*internal.SupportCannedReplyDao
}

var (
	// SupportCannedReply is a globally accessible object for table hg_support_canned_reply operations.
	SupportCannedReply = supportCannedReplyDao{internal.NewSupportCannedReplyDao()}
)


