// =================================================================================
// Manually maintained DAO wrapper (not generated by GoFrame CLI).
// =================================================================================

package dao

import "hotgo/internal/dao/internal"

// supportSessionDao is the data access object for the table hg_support_session.
type supportSessionDao struct {
	*internal.SupportSessionDao
}

var (
	// SupportSession is a globally accessible object for table hg_support_session operations.
	SupportSession = supportSessionDao{internal.NewSupportSessionDao()}
)


