// =================================================================================
// Manually maintained DAO wrapper (not generated by GoFrame CLI).
// =================================================================================

package dao

import "hotgo/internal/dao/internal"

// supportAgentPresenceDao is the data access object for the table hg_support_agent_presence.
type supportAgentPresenceDao struct {
	*internal.SupportAgentPresenceDao
}

var (
	// SupportAgentPresence is a globally accessible object for table hg_support_agent_presence operations.
	SupportAgentPresence = supportAgentPresenceDao{internal.NewSupportAgentPresenceDao()}
)


