// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingStrategyTemplateDao is the data access object for the table hg_trading_strategy_template.
// You can define custom methods on it to extend its functionality as needed.
type tradingStrategyTemplateDao struct {
	*internal.TradingStrategyTemplateDao
}

var (
	// TradingStrategyTemplate is a globally accessible object for table hg_trading_strategy_template operations.
	TradingStrategyTemplate = tradingStrategyTemplateDao{internal.NewTradingStrategyTemplateDao()}
)

// Add your custom methods and functionality below.

