// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingTradeFillDao is the data access object for the table hg_trading_trade_fill.
// You can define custom methods on it to extend its functionality as needed.
type tradingTradeFillDao struct {
	*internal.TradingTradeFillDao
}

var (
	// TradingTradeFill is a globally accessible object for table hg_trading_trade_fill operations.
	TradingTradeFill = tradingTradeFillDao{internal.NewTradingTradeFillDao()}
)

// Add your custom methods and functionality below.
