// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingExecutionLogDao is the data access object for the table hg_trading_execution_log.
// You can define custom methods on it to extend its functionality as needed.
type tradingExecutionLogDao struct {
	*internal.TradingExecutionLogDao
}

var (
	// TradingExecutionLog is a globally accessible object for table hg_trading_execution_log operations.
	TradingExecutionLog = tradingExecutionLogDao{internal.NewTradingExecutionLogDao()}
)

// Add your custom methods and functionality below.

