// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingRobotDao is the data access object for the table hg_trading_robot.
// You can define custom methods on it to extend its functionality as needed.
type tradingRobotDao struct {
	*internal.TradingRobotDao
}

var (
	// TradingRobot is a globally accessible object for table hg_trading_robot operations.
	TradingRobot = tradingRobotDao{internal.NewTradingRobotDao()}
)

// Add your custom methods and functionality below.

