// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingCloseLogDao is the data access object for the table hg_trading_close_log.
// You can define custom methods on it to extend its functionality as needed.
type tradingCloseLogDao struct {
	*internal.TradingCloseLogDao
}

var (
	// TradingCloseLog is a globally accessible object for table hg_trading_close_log operations.
	TradingCloseLog = tradingCloseLogDao{internal.NewTradingCloseLogDao()}
)

// Add your custom methods and functionality below.

