// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingProxyConfigDao is the data access object for the table hg_trading_proxy_config.
// You can define custom methods on it to extend its functionality as needed.
type tradingProxyConfigDao struct {
	*internal.TradingProxyConfigDao
}

var (
	// TradingProxyConfig is a globally accessible object for table hg_trading_proxy_config operations.
	TradingProxyConfig = tradingProxyConfigDao{internal.NewTradingProxyConfigDao()}
)

// Add your custom methods and functionality below.

