// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingApiConfigDao is the data access object for the table hg_trading_api_config.
// You can define custom methods on it to extend its functionality as needed.
type tradingApiConfigDao struct {
	*internal.TradingApiConfigDao
}

var (
	// TradingApiConfig is a globally accessible object for table hg_trading_api_config operations.
	TradingApiConfig = tradingApiConfigDao{internal.NewTradingApiConfigDao()}
)

// Add your custom methods and functionality below.

