// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingOrderDao is the data access object for the table hg_trading_order.
// You can define custom methods on it to extend its functionality as needed.
type tradingOrderDao struct {
	*internal.TradingOrderDao
}

var (
	// TradingOrder is a globally accessible object for table hg_trading_order operations.
	TradingOrder = tradingOrderDao{internal.NewTradingOrderDao()}
)

// Add your custom methods and functionality below.

