// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tradingMonitorLogDao is the data access object for the table hg_trading_monitor_log.
// You can define custom methods on it to extend its functionality as needed.
type tradingMonitorLogDao struct {
	*internal.TradingMonitorLogDao
}

var (
	// TradingMonitorLog is a globally accessible object for table hg_trading_monitor_log operations.
	TradingMonitorLog = tradingMonitorLogDao{internal.NewTradingMonitorLogDao()}
)

// Add your custom methods and functionality below.

